//
//  ShowPaywallSheetWhenCalledModifier.swift
//  InAppPurchaseKit (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/inapppurchasekit/paywall#manually-showing-the-paywall
//

import Foundation
import SharedKit
import SwiftUI

extension InAppPurchases {
	/// Call this function to show the paywall sheet (if the user does not have premium)
	static public func showPaywallSheet() {
		NotificationCenter.default.post(name: Constants.Notifications.InAppPurchases.shouldShowPaywallSheet, object: nil)
	}
}

public struct ShowPaywallSheetWhenCalledModifier: ViewModifier {

	@ObservedObject private var iap: InAppPurchases
	@State private var showSheet: Bool = false

	public init(_ iap: InAppPurchases) {
		self.iap = iap
	}

	public func body(content: Content) -> some View {
		content
			.sheet(isPresented: $showSheet) {
				InAppPurchaseView(
					paywallHeroTitle: "Get Premium Now.",
					onCanceled: {
						showSheet = false
					},
					onComplete: {
						showSheet = false
					})

			}
			.onReceive(
				NotificationCenter.default.publisher(
					for: Constants.Notifications.InAppPurchases.shouldShowPaywallSheet)
			) { _ in
				if iap.subscriptionState == .subscribed { return }
				showSheet = true
			}
	}
}
