//
//  ShowSignInSheetWhenCalledModifier.swift
//  FirebaseKit (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/authkit#show-sign-in-sheet
//

import Foundation
import SharedKit
import SwiftUI

extension DB {
	/// Call this function to show the sign in sheet (if the user is not signed in)
	public func showSignInSheet() {
		NotificationCenter.default.post(name: Constants.Notifications.AuthKit.shouldShowSignInSheet, object: nil)
	}
}

public struct ShowSignInSheetWhenCalledModifier: ViewModifier {

	@ObservedObject var db: DB
	@State var showSheet: Bool = false

	public init(_ db: DB) {
		self.db = db
	}

	public func body(content: Content) -> some View {
		content
			.sheet(isPresented: $showSheet) {
				SignInView(
					db: db,
					navTitle: "Sign in required",
					onSignedIn: {
						showSheet = false
					},
					onCanceled: {
						showSheet = false
					})
			}
			.onReceive(
				NotificationCenter.default.publisher(for: Constants.Notifications.AuthKit.shouldShowSignInSheet)
			) { _ in
				if db.currentUser != nil { return }
				showSheet = true
			}
	}
}
