//
//  AdBanner.swift
//  AdsKit (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/adskit/using-adskit
//

import GoogleMobileAds
import InAppPurchaseKit
import SharedKit
import SwiftUI

/// You can use this View to place AdBanners wherever you need in your app.
/// Make sure to follow Google AdMob guidelines and policies.
/// https://support.google.com/admob/answer/6329638
public struct AdBanner: View {

	@StateObject private var nativeViewModel: NativeAdBannerViewModel
	@EnvironmentObject var iap: InAppPurchases

	public init(adUnitID: String) {
		_nativeViewModel = StateObject(wrappedValue: NativeAdBannerViewModel(adUnitID: adUnitID))
	}

	public var body: some View {
		if iap.subscriptionState != .subscribed {
			NativeAdView(nativeViewModel: nativeViewModel)
				.frame(height: 75)
				.onAppear {
					nativeViewModel.refreshAd()
				}
		} else {
			EmptyView()
		}
	}

	private struct NativeAdView: UIViewRepresentable {
		public typealias UIViewType = GADNativeAdView

		@ObservedObject var nativeViewModel: NativeAdBannerViewModel

		public init(nativeViewModel: NativeAdBannerViewModel) {
			self.nativeViewModel = nativeViewModel
		}

		public func makeUIView(context: Context) -> GADNativeAdView {
			return NativeAdBannerView()
		}

		public func updateUIView(_ nativeAdView: GADNativeAdView, context: Context) {
			guard let nativeAd = nativeViewModel.nativeAd else { return }

			// headline
			if let headlineView = nativeAdView.headlineView as? UILabel {
				headlineView.text = nativeAd.headline
				headlineView.isHidden = false
			} else {
				// no headline present
			}

			// body
			if let bodyView = nativeAdView.bodyView as? UILabel, let bodyContents = nativeAd.body {
				bodyView.text = bodyContents
				bodyView.isHidden = false
			} else {
				// no body present
			}

			// icon
			if let iconView = nativeAdView.iconView as? UIImageView, let iconContents = nativeAd.icon {
				iconView.image = iconContents.image
				iconView.isHidden = false
			} else {
				// no image present
			}

			// button
			if let ctaView = nativeAdView.callToActionView as? UIButton, let ctaContents = nativeAd.callToAction {
				ctaView.isUserInteractionEnabled = false
				ctaView.setTitle(ctaContents, for: .normal)
				ctaView.isHidden = false
			} else {
				// no cta button present
			}

			// Associate the native ad view with the native ad object. This is required to make the ad clickable.
			// Note: this should always be done after populating the ad views.
			nativeAdView.nativeAd = nativeAd
		}
	}
}

#Preview {
	AdBanner(adUnitID: "ca-app-pub-3940256099942544/3986624511")
		.environmentObject(InAppPurchases())
}
