//
//  SignUpView.swift
//  FirebaseKit (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/authkit/email-sign-in-flow#account-creation--email-verification
//

import AnalyticsKit
import SharedKit
import SwiftUI

struct SignUpView: View {

	@EnvironmentObject var db: DB

	var body: some View {

		VStack {

			Spacer()

			HeroView(
				sfSymbolName: "person.crop.circle.badge.plus",
				title: "Create an Account.")
			Spacer()

			EmailInputFields { email, password in
				Task {
					await tryFunctionOtherwiseShowInAppNotification(
						fallbackNotificationContent: .init(
							title: "Couldn't Create Account",
							message: "Try Again Later"
						)
					) {
						try await db.signUp(email: email, password: password)
						showInAppNotification(
							.success,
							content: .init(
								title: "Successfully Signed Up!",
								message: "We've sent you a verification email"
							),
							size: .compact
						)
					}
				}
			}
		}
		.padding()
		.navigationTitle("Sign Up")
		.captureViewActivity(as: "SignUpView")
	}
}

#Preview {
	VStack {
		SignUpView()
			.environmentObject(DB())
	}

}
