//
//  Ads.swift
//  AdsKit (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/adskit
//

import Foundation
import GoogleMobileAds

public class Ads {
	// Used once in App.swift to initialize GoogleMobileAds
	public static func initGoogleMobileAds() {
		GADMobileAds.sharedInstance().start(completionHandler: nil)
		// see https://docs.swiftylaun.ch/project-setup/adskit#setting-test-device-id
		// GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ "TEST_DEVICE_IDENTIFIER" ]
	}
}
