//
//  accentBackground.swift
//  SharedKit (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/sharedkit/ui
//

import SwiftUI

struct AccentBackground: ViewModifier {

	let strong: Bool

	func body(content: Content) -> some View {
		content
			.background(
				LinearGradient(
					colors: [
						Color.accent.opacity(strong ? 0.2 : 0.075),
						Color(uiColor: .secondarySystemBackground),
					], startPoint: .topLeading,
					endPoint: .bottomTrailing)
			)
	}
}

extension View {
	/// Give the background a slight accent color tint. Great for sheets
	public func accentBackground(strong: Bool = false) -> some View {
		modifier(AccentBackground(strong: strong))
	}
}

#Preview {
	HeroView(sfSymbolName: "person.fill", title: "Example View")
		.frame(maxWidth: .infinity, maxHeight: .infinity)
		.accentBackground(strong: true)
}
