//
//  NotificationsSettingsView.swift
//  NotifKit (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/notifkit#view--notificationssettingsviewswift
//

import SwiftUI

public struct NotificationsSettingsView: View {

	@Environment(\.scenePhase) private var scenePhase
	@State private var notificationsAllowed: Bool = false

	public init() {}

	func checkIfHasAccess() async {
		notificationsAllowed = await PushNotifications.hasNotificationsPermission()
	}

	public var body: some View {
		VStack {
			if !notificationsAllowed {
				NotificationsPermissionView()
			} else {
				Text("Custom Notification Settings here...")
			}
		}
		.navigationTitle("Notifications")
		.onAppearAndChange(of: scenePhase) {  // Maybe the user has changed the notifications settings in the settings app and came back
			Task {
				await checkIfHasAccess()
			}
		}
	}
}

#Preview {
	NotificationsSettingsView()
}
