//
//  CheckmarkToggle.swift
//  SharedKit (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/sharedkit/ui/check-toggle-style
//

import SwiftUI

/// Use this view if you want to use the checkmark for things other than toggle (e.g. for a button)
public struct CheckmarkToggle: View {
	var checked: Bool
	let onToggle: (() -> Void)

	public init(checked: Bool, onToggle: @escaping (() -> Void) = {}) {
		self.checked = checked
		self.onToggle = onToggle
	}

	public var body: some View {
		Image(systemName: checked ? "checkmark.circle.fill" : "circle")
			.fontWeight(.semibold)
			.foregroundStyle(checked ? Color.accent : .secondary)
			.accessibilityLabel(Text(checked ? "Checked" : "Unchecked"))
			.imageScale(.large)
			.animation(.easeInOut(duration: 0.15), value: checked)
			.onTapGesture {
				onToggle()
			}
	}
}

/// Toggle Style to inherit the CheckToggle Design
public struct CheckToggleStyle: ToggleStyle {
	public func makeBody(configuration: Configuration) -> some View {
		Button {
			configuration.isOn.toggle()
		} label: {
			Label {
				configuration.label
			} icon: {
				CheckmarkToggle(checked: configuration.isOn) {
					configuration.isOn.toggle()
				}
			}
		}
		.buttonStyle(.plain)
	}
}

private struct PreviewView: View {

	@State var isCheckedOne: Bool = false
	@State var isCheckedTwo: Bool = true

	var body: some View {
		VStack(spacing: 20) {
			Toggle("Checkmark Toggle", isOn: $isCheckedOne)
				.toggleStyle(CheckToggleStyle())
				.font(.largeTitle)

			Toggle("Checkmark Toggle", isOn: $isCheckedTwo)
				.toggleStyle(CheckToggleStyle())
				.font(.largeTitle)

		}
	}
}

#Preview {
	PreviewView()
}
