//
//  onAppearAndChange.swift
//  SharedKit (Generated by SwiftyLaunch 2.0)
//

import SwiftUI

extension View {
	/// Will execute `action()` on appear and when `value` changes.
	@ViewBuilder public func onAppearAndChange<V>(
		of value: V,
		perform action: @escaping () -> Void
	) -> some View where V: Equatable {
		self
			.onAppear {
				action()
			}
			.onChange(of: value) {
				action()
			}
	}

}

private struct PreviewView: View {

	@State var value: Int = 0

	var body: some View {
		VStack {
			Text("Value: \(value)")
			Button("Increase by one") {
				value += 1
			}
			.onAppearAndChange(of: value) {
				print("New Value: \(value)")
			}
		}
	}
}

#Preview {
	PreviewView()
}
