//
//  HeroView.swift
//  SharedKit (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/sharedkit/ui#hero-view-component
//

import SwiftUI

public enum HeroViewSize {

	/// Perfect for views that only partially cover the screen
	case small

	/// Perfect for full screen views (e.g. email verification screen)
	case large
}

/// Display important information with this view.
public struct HeroView: View {

	private let sfSymbolName: String
	private let title: LocalizedStringKey
	private let subtitle: LocalizedStringKey?
	private let size: HeroViewSize

	//When this value is changed -> Bounce
	@State var bounceOnChangeOfThisValue: Bool

	public init(
		sfSymbolName: String,
		title: LocalizedStringKey,
		subtitle: LocalizedStringKey? = nil,
		size: HeroViewSize = .large,
		bounceOnAppear: Bool = false
	) {
		self.sfSymbolName = sfSymbolName
		self.title = title
		self.subtitle = subtitle
		self.size = size
		self._bounceOnChangeOfThisValue = State(initialValue: bounceOnAppear)
	}

	public var body: some View {
		VStack {
			Image(systemName: sfSymbolName)
				.symbolRenderingMode(.hierarchical)
				.foregroundStyle(Color.accent)
				.font(.system(size: size == .large ? 125 : 75, weight: .semibold))
				.padding(.bottom, size == .large ? 10 : 5)
				.symbolEffect(.bounce, value: bounceOnChangeOfThisValue)

			Text(title)
				.font(.largeTitle)
				.bold()
				.multilineTextAlignment(.center)

			if let subtitle = subtitle {
				Text(subtitle)
					.font(.callout)
					.multilineTextAlignment(.center)
					.foregroundStyle(.secondary)
			}
		}
		.onAppear {
			Task {
				// Because we set this value to the value of bounceOfAppear in init, we can just use this to
				// check if we should bounce on appear
				if bounceOnChangeOfThisValue {
					// Bounce 0.15 seconds after appear
					try? await Task.sleep(for: .seconds(0.2))
					bounceOnChangeOfThisValue.toggle()
				}
			}
		}
	}
}

private struct PreviewView: View {

	var body: some View {
		VStack {
			HeroView(
				sfSymbolName: "envelope.badge",
				title: "Check your Inbox.",
				subtitle: "An email with a verification link\nwas sent to your@email.com",
				bounceOnAppear: true
			)
		}
	}

}

#Preview { PreviewView() }
