//
//  isPreview.swift
//  SharedKit (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/sharedkit/helper-functions/check-if-in-swiftui-preview
//

import Foundation

///Will return whether the code is running in a SwiftUI Preview (For Xcode Previews)
public var isPreview: Bool {
	return ProcessInfo.processInfo.environment["XCODE_RUNNING_FOR_PREVIEWS"] == "1"
}
