//
//  openAppInSettings.swift
//  SharedKit (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/sharedkit/helper-functions/open-app-in-settings
//

import SwiftUI

/// Will open the settings app with our app's settings
/// Always returns false.
@discardableResult
public func openAppInSettings() -> Bool {
	UIApplication.shared.open(URL(string: UIApplication.openSettingsURLString)!)
	/// Just for convenience, so we can use the same function type as in RequestType.requestAction
	return false
}
