//
//  AdsKitExamples.swift
//  AdsKit (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/adskit
//

import GoogleMobileAds
import InAppPurchaseKit
import SwiftUI

public struct AdsKitExamples: View {

	@EnvironmentObject var iap: InAppPurchases

	public init() {}

	public var body: some View {
		NavigationStack {
			VStack {

				// replace this test ad unit id with your actual ad unit id
				AdBanner(adUnitID: "ca-app-pub-3940256099942544/3986624511")

				Spacer()
				if iap.subscriptionState != .subscribed {
					Text("Ads are shown because you have no premium.")
				} else {
					Text("Ads are not shown because you have premium access.")
				}

				Spacer()
			}
			.navigationTitle("AdsKit Showroom")
			.navigationBarTitleDisplayMode(.inline)
		}
	}
}

#Preview {
	AdsKitExamples()
		.environmentObject(InAppPurchases())
}
