//
//  PrivacyView.swift
//  App (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/app/views/app-settings#privacy-settings-screen
//

import AnalyticsKit
import SharedKit
import SwiftUI

// Note: Dont forget to show the Privacy Policy and Terms of Service of your App in the App Store Connect
// You *MUST* include these in order to activate in-app purchases
struct PrivacyView: View {

	@State private var showPrivacyPolicy = false
	@State private var showToS = false

	var body: some View {
		VStack {
			List {
				Section {
					Button("Privacy Policy") {
						showPrivacyPolicy = true
					}

					Button("Terms of Service") {
						showToS = true
					}
				}

			}
		}
		.navigationTitle("Privacy")
		.webViewSheet($showPrivacyPolicy, url: URL(string: Constants.AppData.privacyPolicyURL)!, title: "Privacy Policy")
		.webViewSheet($showToS, url: URL(string: Constants.AppData.termsOfServiceURL)!, title: "Terms of Service")
		.captureViewActivity(as: "PrivacyView")
	}
}

#Preview {
	NavigationStack {
		PrivacyView()
	}
}
